blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('blogs.main')),
    url(r'^blog/', include('blogs.urls', namespace='blog')),
    url(r'^api/', include('blogs.api')),
    url(r'^movie/', include('movie.urls',namespace='movie')),
    url(r'^book/',include('books.urls',namespace='books'))
]

blogs/urls.py
# encoding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    # ^$约束空字符串 ^index/$分号很重要
    url(r'^$', views.blog_index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name="edit_page"),
    url(r'^edit_action/$', views.edit_action, name="edit_action"),
    url(r'^index', views.index),
    url(r'^article_detail/(?P<article_id>[0-9]+)$',views.article_page)

]

blogs/models.py
#encoding=utf-8
from __future__ import unicode_literals
from django.db import models


class Article(models.Model):
    # 博客标题定义为字符串，最大长度为32默认值是title

    title = models.CharField(max_length=32, default='Title')
    author = models.CharField(null=True, max_length=16)
    image_url = models.CharField(max_length=255, null=True)
    abstract = models.TextField(null=True)
    # 定义blog的内容，内容可以为空
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)
    state = models.IntegerField(default=0) #0表示一般文章，1表示推荐

    def __str__(self):
        return self.title

blogs/views.py
#encoding=utf-8
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from . import models
import sys
import json
import datetime

reload(sys)
sys.setdefaultencoding('utf-8')


# 参考方法2：增加了日期类型判断
def convert_obj_to_dicts(model_obj):
    object_array = []
    for obj in model_obj:
        # 获取到所有属性
        # field_names_list = obj._meta.fields
        fields = []
        for field in obj._meta.fields:
            fields.append(field.name)

        for fieldName in fields:
            print fieldName
            try:
                fieldValue = getattr(obj, fieldName)  # 获取属性值
                print type(fieldValue)
                if type(fieldValue) is datetime.date or type(fieldValue) is datetime.datetime:
                    #                     fieldValue = fieldValue.isoformat()
                    fieldValue = datetime.datetime.strftime(fieldValue, '%Y-%m-%d %H:%M:%S')
                    # 没想好外键与cache字段的解决办法
                #                 if hasattr(fieldValue, "__dict__"):
                #                     fieldValue = convert_obj_to_dicts(model_obj)
                setattr(obj, fieldName, fieldValue)
            # print fieldName, "\t", fieldValue
            except Exception, ex:
                print ex
                pass
                # 先把Object对象转换成Dict
        dict = {}
        dict.update(obj.__dict__)
        dict.pop("_state", None)  # 此处删除了model对象多余的字段
        object_array.append(dict)
    return object_array

def blog_index(request):
    # pk 是Primary key主键的意思即为文章id
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, "blog/html/article_detail.html", {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, "blog/edit_page.html")
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})

    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, "blog/article_page.html", {'article': article})

def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/html/index.html', {'articles': articles})

def main(request):
    articles = models.Article.objects.all()
    return render(request,'main.html',{'articles':articles})


def api_getAll_article(request):
    articles = models.Article.objects.all()
    json_data = convert_obj_to_dicts(articles)
    # return JsonResponse(json.d)
    return HttpResponse(json.dumps(json_data), content_type="application/json")

templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客</title>
</head>
<body>
<h1>{{ article.title }}</h1>
</br>
<div>
{% autoescape off %}
    {{article.content}}
{% endautoescape %}
</div>
</br>
<a href="{% url 'blog:edit_page' article.id%}">修改文章</a>
</body>
</html>

templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
    <labe>文章标题
        <input type="text" name="title" value="{{ article.title }}">
    </labe>
    </br></br>
    <label>文章内容
        <input type="text" name="content" value="{{ article.content }}">
    </label>
    </br></br>
    <input type="submit" value="提交">
</form>
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> <a href="{% url 'blog:edit_page' '0'%}">添加新文章</a> </h1>
{% for article in articles%}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title}}</a>
    </br>
{% endfor %}
</body>
</html>